name: m3u
version: 1.0.0
homepage: https://github.com/bmoliveira/m3u-parse-utils
author: Bruno Oliveira <bm.oliveira.dev@gmail.com>
description: Simple Dart tool to parse M3U and M3U_Plus files from a string or document string.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.3.0
