name: m3u
version: 0.0.2
homepage: https://github.com/bmoliveira/m3u-parse-utils
author: Bruno Oliveira <bm.oliveira.dev@gmail.com>
description: M3U file parser.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.3.0
